// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahczgeietyhwrycwlbhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoY3pnZWlldHlod3J5Y3dsYmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDEwNDUsImV4cCI6MjA3MzM3NzA0NX0.OJJmjKUOpA52GGZOkVp0oL8CHkhtK8kO2qk86E2kt0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});